### ISSUE TITLE
Animated images bug

### ISSUE THREAD

**Issue by MasterCruelty** [NespoliBT/nespolibt.com#4]
I visited the website [nespolibt.com](https://nespolibt.com) and I've seen animated images are partially outside of my screen.

Check it out 😎

**Comment by archetipico** [comment]
I second that. I don't know if it's intended but I see the margin-left is set to -120px without changing. That should be increased when hovering.

**Comment by MasterCruelty** [comment]
Indeed. I hope it will be fixed 🐛

**Comment by archetipico** [comment]
Is this repo alive?

**Comment by archetipico** [comment]
Now I fully understand the problem: on mobile nothing is wrong, the problem persists on desktop.
A possible fix would be to remove the ` justify-content: space-between;` in `.project.svelte-cbpt41.svelte-cbpt41` (boundle.css). This will keep the wobble effect while justifying the image even for desktop users.

**Comment by MasterCruelty** [comment]
Nice!

**Comment by MasterCruelty** [comment]
> Now I fully understand the problem: on mobile nothing is wrong, the problem persists on desktop.
> A possible fix would be to remove the ` justify-content: space-between;` in `.project.svelte-cbpt41.svelte-cbpt41` (boundle.css). This will keep the wobble effect while justifying the image even for desktop users.

@NespoliBT Do you agree with this solution?

**Comment by NespoliBT** [comment]
> @NespoliBT Do you agree with this solution?

I quite like this solution, I have implemented the fix as @archetipico suggested.

Closing
